on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run-ci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v6
        - uses: actions-rust-lang/setup-rust-toolchain@v1
          with:
            components: clippy, rustfmt
            target: wasm32-wasip2
        - uses: extractions/setup-just@v3
        # Install cargo binstall to remove compilation time for dependencies.
        - run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
        # This has to be force, as the registry for if wkg is installed can be incorrect.
        - run: cargo binstall wkg --no-confirm --force

        - name: "formatting-check"
          run: |
            echo "PATH=$PATH"
            which wkg || ls -la $HOME/.cargo/bin
            just format-check

        - name: "compile-check"
          # Makes warnings be treated as errors (be output to STDERR), so that the pipeline can pick up on warnings.
          run: RUSTFLAGS="--deny warnings" just build

        - name: "test-check"
          run: just test

        - name: "quality-check"
          run: just quality-check
